// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Top25NBAPlayers.Data;

namespace Top25NBAPlayers.Data.Migrations
{
    [DbContext(typeof(Top25NBAPlayersContext))]
    [Migration("20190311232715_initialMigration2")]
    partial class initialMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Top25NBAPlayers.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Deleted_Ind");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Top25NBAPlayers.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AllStars");

                    b.Property<string>("Avatar");

                    b.Property<int>("Championships");

                    b.Property<int>("Deleted_Ind");

                    b.Property<int>("JerseyNumber");

                    b.Property<int>("Mvps");

                    b.Property<string>("Name");

                    b.Property<double>("SeasonAssists");

                    b.Property<double>("SeasonFieldGoalPercentage");

                    b.Property<double>("SeasonPoints");

                    b.Property<double>("SeasonRebounds");

                    b.Property<Guid>("TeamId");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Top25NBAPlayers.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Championships");

                    b.Property<int>("Deleted_Ind");

                    b.Property<string>("GreatestPlayer");

                    b.Property<int?>("LastChampionship");

                    b.Property<string>("Logo");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
